# Generated by Django 3.1.5 on 2021-02-01 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210129_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='lister_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_lister', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='winner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
