# Generated by Django 3.1.5 on 2021-02-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210204_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='current_price',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.auctionlisting'),
        ),
    ]
