# Generated by Django 3.1.5 on 2021-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210204_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_listing',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_listing',
            field=models.ManyToManyField(related_name='bid', to='auctions.AuctionListing'),
        ),
    ]
