# Generated by Django 3.1.5 on 2021-02-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210204_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('1', 'Devil Fruit'), ('2', 'Weapon'), ('3', 'Transportation'), ('4', 'Food'), ('5', 'Rare Item'), ('6', 'Crewmate')], default=('2', 'Weapon'), max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
